-- Agenda ao Ar Livre: referência PostgreSQL de domínio, Fase 1.
-- Não substitui migrations ou tabelas técnicas do Django.
CREATE TABLE usuario (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 email varchar(254) NOT NULL, nome varchar(150) NOT NULL,
 password varchar(128) NOT NULL, is_active boolean NOT NULL DEFAULT true,
 is_staff boolean NOT NULL DEFAULT false, is_superuser boolean NOT NULL DEFAULT false,
 date_joined timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, last_login timestamptz,
 CHECK (email = lower(email)), CHECK (length(trim(nome)) > 0)
);
CREATE UNIQUE INDEX usuario_email_lower_uniq ON usuario(lower(email));
CREATE TABLE local (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 proprietario_id bigint NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
 nome varchar(120) NOT NULL, endereco varchar(255) NOT NULL,
 cidade varchar(120) NOT NULL, uf char(2) NOT NULL,
 latitude numeric(9,6) NOT NULL CHECK(latitude BETWEEN -90 AND 90),
 longitude numeric(9,6) NOT NULL CHECK(longitude BETWEEN -180 AND 180),
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CHECK (uf IN ('AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'))
);
CREATE TABLE categoria (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome varchar(60) NOT NULL UNIQUE CHECK(length(trim(nome)) > 0)
);
CREATE TABLE atividade (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 organizador_id bigint NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
 local_id bigint NOT NULL REFERENCES local(id) ON DELETE RESTRICT,
 categoria_id bigint NOT NULL REFERENCES categoria(id) ON DELETE RESTRICT,
 titulo varchar(120) NOT NULL, descricao text NOT NULL,
 inicio timestamptz NOT NULL, termino timestamptz NOT NULL,
 capacidade integer NOT NULL CHECK(capacidade BETWEEN 1 AND 500),
 situacao varchar(12) NOT NULL DEFAULT 'rascunho' CHECK(situacao IN ('rascunho','publicada','cancelada')),
 motivo_cancelamento varchar(500) NOT NULL DEFAULT '', cancelada_em timestamptz,
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CHECK(termino > inicio), CHECK(length(trim(titulo)) > 0),
 CHECK(length(descricao) BETWEEN 10 AND 5000),
 CHECK((situacao = 'cancelada' AND cancelada_em IS NOT NULL AND length(motivo_cancelamento) BETWEEN 10 AND 500)
 OR (situacao <> 'cancelada' AND cancelada_em IS NULL AND motivo_cancelamento = ''))
);
CREATE TABLE inscricao (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 usuario_id bigint NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
 atividade_id bigint NOT NULL REFERENCES atividade(id) ON DELETE RESTRICT,
 situacao varchar(12) NOT NULL CHECK(situacao IN ('confirmada','cancelada')),
 motivo_cancelamento varchar(20) NOT NULL DEFAULT '',
 criado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 atualizado_em timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 cancelada_em timestamptz,
 UNIQUE(usuario_id, atividade_id),
 CHECK((situacao = 'confirmada' AND cancelada_em IS NULL AND motivo_cancelamento = '')
 OR (situacao = 'cancelada' AND cancelada_em IS NOT NULL AND motivo_cancelamento IN ('participante','atividade_cancelada')))
);
CREATE INDEX atividade_busca_idx ON atividade(situacao,inicio,id);
CREATE INDEX atividade_organizador_idx ON atividade(organizador_id,inicio);
CREATE INDEX local_cidade_idx ON local(cidade);
CREATE INDEX inscricao_contagem_idx ON inscricao(atividade_id,situacao);
-- FKs adicionais são indexadas automaticamente por models.ForeignKey no Django.
-- Regras entre tabelas, capacidade e autorizações: serviço transacional.
